### PR TITLE
Renderer integration

### PR DESCRIPTION
**Pull request by douira**
The part that makes the LaTeX code from the resolutions. Integrates the LaTeX code written previously, into the generator. Currently incomplete.

### CODE REVIEW

**Comment by TomTomRixRix** [comment]
Great, I didn't realize that you pushed on the rendering that much. 

I tried to implement the extended clauses in an offline version of the template, that works fine as well. I'll commit them soon on this branch, but at the moment I somehow can't get the app running and can't test it.

What features are still missing to finish the rendering?

**Comment by douira** [comment]
These are the open issues for rendering: #104 (special string styling) and #48 (spacing in the preambs  is still wrong)
And extended content still needs the template and generator code. This will also entail some logic reworking of the generator as the punctuation gets more complicated through content that can occupy the last place even after the subclauses. (I've worked this out in the liveview renderer though so copying it over won't be too hard).

**Comment by douira** [comment]
merged liveview into this branch. Create liveview-4 to continue development on liveview.

**Comment by douira** [comment]
@TomTomRixRix Preamb clauses with subclauses but no extended content cause this error: `LaTeX Error: There's no line here to end.` This is confirmed not to happen when there are no subclauses or when extended content is present. This is also not a format incompatibility problem.

**Comment by TomTomRixRix** [comment]
I've solved the bug. It was indeed a problem that there is no content in the line (because the extended content is missing) but our code wanted to do two line breaks. To fix this I've changed a `\newline` command to a `\par` command which is the prettier way anyways :smile:

Here is a sample resolution demonstrating that the bug is fixed

grafik

**Comment by douira** [comment]
The line break between the preamb and the first op clause looks pretty big although it should actually only be one line. I don't think we want the spacing become inconsistent or too long

**Comment by TomTomRixRix** [comment]
Yes, I'll check if it's just because of this screen shot or if it's a general problem. Perhaps we have to change some settings for the `par `command because the default settings add a bit of vertical space. This should however be fixed easily.

**Comment by douira** [comment]
Good idea!

**Pull request merged**
